# -*- coding: utf-8 -*-
"""tabla

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sfroVbJzEMrNTKfiBa__0QPw7giBicAU
"""

def tabla():
  n1= int(input("INGRESE EL PRIMER NÚMERO ENTERO POSITIVO DEL 1 AL 9: "))
  while not(n1 > 0 and n1 < 10):
    if n1 <= 0 or n1 >= 10:
      n1 = int(input("\nERROR\nPARA UTILIZAR ESTE SCRIPT, DEBE INGRESAR 2 NÚMEROS ENTEROS POSITIVOS DEL 1 AL 9.\nPor favor, ingrese el primer número correctamente: "))

  n2= int(input("INGRESE EL SEGUNDO NÚMERO ENTERO POSITIVO DEL 1 AL 9: "))
  while not(n2 > 0 and n2 < 10):
    if n2 <= 0 or n2 >= 10:
      n2 = int(input("\nERROR\nPARA UTILIZAR ESTE SCRIPT, DEBE INGRESAR 2 NÚMEROS ENTEROS POSITIVOS DEL 1 AL 9.\nPor favor, ingrese el segundo número correctamente: "))

  for i in range(n1):
    for e in range(n2):
      print("*", end='')
    print("")